libraries/accounts/urls.py
from django.urls import path, re_path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('register/request', views.RegisterRequestView.as_view(), name='registration'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('login/request', views.LoginRequestView.as_view(), name='login_request'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('change/', views.PasswordChangeView.as_view(), name='change'),
    path('recover/', views.PasswordRecoverView.as_view(), name='recover'),
]

libraries/libraries/urls.py
from django.contrib import admin
from django.urls import path, include
from libraries.views import *

from django.contrib.auth.models import User
from rest_framework import serializers, viewsets, routers

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


urlpatterns = [
    path('admin/', admin.site.urls),
    # main dashboard
    path('', HomeView.as_view(), name='home'),
    path('all/', DataView.as_view(), name='all'),
    path('si/', SiDataView.as_view(), name='si'),
    path('gun/<str:name>', GunDataView.as_view(), name='gun'),
    # apps
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('search/', include('search.urls')),
    # rest api
    path('libraries/', include('api_library.urls'), name='api_library'),
]

libraries/rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = [
        ...
        path('auth/', include('rest_framework.urls'))
    ]

You should make sure your authentication settings include `SessionAuthentication`.
"""
from django.contrib.auth import views
from django.urls import path

app_name = 'rest_framework'
urlpatterns = [
    path('login/', views.LoginView.as_view(template_name='rest_framework/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

libraries/search/urls.py
from django.urls import path, re_path
from search import views

app_name = 'search'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('all/', views.AllLibraryListView.as_view(), name='all'),
    path('list/<str:name>', views.LibraryListView.as_view(), name='list'),
    # path('detail/', views.DetailView.as_view(), name='detail_view'),
    path('detail/<str:name>', views.LibraryDetailView.as_view(), name='detail'),
    path('detail/naver/<str:name>', views.SearchNaverView.as_view(), name='naver'),
]

libraries/accounts/models.py
from django.db import models

# Create your models here.

libraries/accounts/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView
from django.contrib.auth.models import User
from django.contrib import auth
from django.conf import settings

class RegisterView(TemplateView):
    template_name = 'accounts/register.html'

class RegisterRequestView(View):
    def post(self, request):
        if request.method == "POST":
            if request.POST["password"] == request.POST["repeat-password"]:
                user = User.objects.create_user(username=request.POST["username"],\
                                                password=request.POST["password"],\
                                                email=request.POST["email"])
                return render(request, 'accounts/register_done.html')

            return render(request, 'accounts/register.html')

class LoginView(TemplateView):
    template_name = 'accounts/login.html'

class LoginRequestView(View):
    def post(self, request):
        if request.method == "POST":
            user = User.objects.get_by_natural_key(request.POST["username"])
            if user.check_password(request.POST['password']):
                auth.login(request, user)
                request.session['username'] = user.username
                request.session['is_active'] = user.is_active
                remember = request.POST.get('auto', False)

                if remember=='on':
                    request.session['remember'] = True
                    settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = False
                else:
                    request.session['remember'] = False
                    settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = True
                    request.session.set_expiry(1800)
                return render(request, 'home.html')

            return render(request, 'accounts/login.html')

class LogoutView(View):
    def get(self, request):
        auth.logout(request)
        request.session.clear()
        return redirect('/')

# 아래는 폼 요소 처리 필요
class PasswordChangeView(TemplateView):
    template_name = 'accounts/password_change.html'

class PasswordRecoverView(TemplateView):
    template_name = 'accounts/password_recovery.html'

libraries/accounts/templates/accounts/login.html
{% extends 'base_auth.html' %}

{% load static%}

{% block title %}Login{% endblock %}

{% block heading %}PLEASE LOGIN TO APP{% endblock %}

{% block simple-explain %}This is the best app ever!{% endblock %}

{% block content %}
<form action="{% url 'accounts:login_request' %}" id="loginForm" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label class="control-label" for="username">Username</label>
        <input type="text" placeholder="example@gmail.com" title="Please enter you username" required="" value=""
               name="username" id="username" class="form-control">
        <span class="help-block small">Your unique username to app</span>
    </div>
    <div class="form-group">
        <label class="control-label" for="password">Password</label>
        <input type="password" title="Please enter your password" placeholder="******" required="" value=""
               name="password" id="password" class="form-control">
        <span class="help-block small">Your strong password</span>
    </div>
    <div class="checkbox login-checkbox">
        <label>
            <input type="checkbox" class="i-checks" name="auto"> Remember me </label>
        <span class="help-block small">if you don't check this option, your login connection will expire in 30 minutes.</span>
    </div>
    <div class="text-center">
        <span class="help-block small" style="visibility:hidden;">hello</span>
        <input type="submit" class="btn btn-success btn-block loginbtn" value="Login">
        <a class="btn btn-default btn-block" href="{% url 'accounts:register' %}">Register</a>
    </div>
</form>

{% endblock %}

libraries/accounts/templates/accounts/password_change.html
{% extends 'base_auth.html' %}

{% load static%}

{% block title %}Password Change{% endblock %}

{% block heading %}PASSWORD CHANGE{% endblock %}

{% block simple-explain %}Please fill the form to change your password{% endblock %}

{% block content %}
<p>
    Enter your old password for security's sake, and then enter your new password twice.
</p>
<form action="." id="loginForm" method="post">{% csrf_token %}
    <div class="form-group">
        <div class="form-group col-lg-6">
            <label>Old password</label>
            <input type="password" class="form-control">
        </div>
        <div class="form-group col-lg-6">
            <label>New password</label>
            <input type="password" class="form-control">
        </div>
        <div class="form-group col-lg-6">
            <label>New password confirmation</label>
            <input type="password" class="form-control">
        </div>
        <div class="text-center">
            <button class="btn btn-success loginbtn">Change</button>
            <button class="btn btn-default cancelbtn">Cancel</button>
        </div>
    </div>

    <button class="btn btn-success btn-block">Reset password</button>
</form>
{% endblock %}

{% block extra-script %}
<script>
    $(function(){
        $('.cancelbtn').on('click', function(event) {
            event.preventDefault();
            event.stopPropagation();
            history.back();
        })
    });
</script>
{% endblock%}

libraries/accounts/templates/accounts/password_change_done.html
{% extends 'base_auth.html' %}

{% load static%}

{% block title %}Password Change Done{% endblock %}

{% block heading %}Changing password is DONE !!{% endblock %}

libraries/accounts/templates/accounts/password_recovery.html
{% extends 'base_auth.html' %}

{% load static%}

{% block title %}Password Recevery{% endblock %}

{% block heading %}PASSWORD RECOVER{% endblock %}

{% block simple-explain %}Please fill the form to recover your password{% endblock %}

{% block content %}
<p>
    Enter your email address and your password will be reset and emailed to you.
</p>
<form action="." id="loginForm" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label class="control-label" for="username">Email</label>
        <input type="text" placeholder="example@gmail.com" title="Please enter you email adress" required="" value=""
               name="username" id="username" class="form-control">
        <span class="help-block small">Your registered email address</span>
    </div>

    <button class="btn btn-success btn-block">Reset password</button>
</form>
{% endblock %}

libraries/accounts/templates/accounts/register.html
{% extends 'base_auth.html' %}

{% load static%}

{% block title %}Register{% endblock %}

{% block heading %}Registeration{% endblock %}

{% block content %}
<!-- 현재와 동일한 url로 폼 요청 -->
<form action="{% url 'accounts:registration' %}" id="loginForm" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="form-group col-lg-12">
            <label>Username</label>
            <input class="form-control" name="username">
        </div>
        <div class="form-group col-lg-6">
            <label>Password</label>
            <input type="password" class="form-control" name="password">
        </div>
        <div class="form-group col-lg-6">
            <label>Repeat Password</label>
            <input type="password" class="form-control" name="repeat-password">
        </div>
        <div class="form-group col-lg-6">
            <label>Email Address</label>
            <input class="form-control" name="email">
        </div>
        <div class="form-group col-lg-6">
            <label>Address</label>
            <input class="form-control" name="address">
        </div>
        <div class="checkbox col-lg-12">
            <input type="checkbox" class="i-checks" checked> Sigh up for our newsletter
        </div>
    </div>
    <div class="text-center">
        <input class="btn btn-success loginbtn register-btn" type="submit" value="Register">
<!--        <button class="btn btn-success loginbtn register-btn">Register</button>-->
        <button class="btn btn-default cancel-btn">Cancel</button>
    </div>
</form>
{% endblock %}

{% block extra-script %}
<script>
    $(function () {
        $('.cancel-btn').on('click', function(event){
            event.preventDefault();
            event.stopPropagation();
            history.back();
        })
    });
</script>
{% endblock %}

libraries/accounts/templates/accounts/register_done.html
{% extends 'base_auth.html' %}

{% load static%}

{% block title %}Register Done{% endblock %}

{% block heading %}Registeration is DONE !!{% endblock %}

{% block content %}
<a href="{% url 'accounts:login' %}" class="btn btn-success btn-block loginbtn">Login</a>
{% endblock %}

{% block extra-script %}
<script>
</script>
{% endblock %}