libraries/libraries/urls.py
from django.contrib import admin
from django.urls import path, include
from libraries.views import *

from django.contrib.auth.models import User
from rest_framework import serializers, viewsets, routers

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


urlpatterns = [
    path('admin/', admin.site.urls),
    # main dashboard
    path('', HomeView.as_view(), name='home'),
    path('all/', DataView.as_view(), name='all'),
    path('si/', SiDataView.as_view(), name='si'),
    path('gun/<str:name>', GunDataView.as_view(), name='gun'),
    # apps
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('search/', include('search.urls')),
    # rest api
    path('libraries/', include('api_library.urls'), name='api_library'),
]

libraries/rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = [
        ...
        path('auth/', include('rest_framework.urls'))
    ]

You should make sure your authentication settings include `SessionAuthentication`.
"""
from django.contrib.auth import views
from django.urls import path

app_name = 'rest_framework'
urlpatterns = [
    path('login/', views.LoginView.as_view(template_name='rest_framework/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

libraries/search/urls.py
from django.urls import path, re_path
from search import views

app_name = 'search'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('all/', views.AllLibraryListView.as_view(), name='all'),
    path('list/<str:name>', views.LibraryListView.as_view(), name='list'),
    # path('detail/', views.DetailView.as_view(), name='detail_view'),
    path('detail/<str:name>', views.LibraryDetailView.as_view(), name='detail'),
    path('detail/naver/<str:name>', views.SearchNaverView.as_view(), name='naver'),
]

libraries/search/views.py
import json
from datetime import datetime
from django.shortcuts import render
from django.views.generic.base import View,TemplateView
from django.http import HttpResponse
from dao.searchLibrary import SearchManager
from dao.requestNaverApi import NaverApi

class IndexView(TemplateView):
    template_name = 'search/index.html'

class AllLibraryListView(View):
    def __init__(self):
        self.sm = SearchManager('localhost', 'ssacuser', 'ssac123!@#', 'libweb')

    def get(self, request):
        self.basic_list = self.sm.getBasicInfo()
        status = Status().getStatus(self.sm, self.basic_list)
        for i in range(len(self.basic_list)):
            if self.basic_list[i]['name'] == status[i]['name']:
                self.basic_list[i]['status'] = status[i]['status']
        result = json.dumps(self.basic_list, ensure_ascii=False)
        self.sm.close()
        return HttpResponse(result, content_type="application/json")

class LibraryListView(View):
    def __init__(self):
        self.sm = SearchManager('localhost', 'ssacuser', 'ssac123!@#', 'libweb')

    def get(self, request, name):
        self.basic_list = self.sm.getBasicInfo(name=name)
        status = Status().getStatus(self.sm, self.basic_list)
        for i in range(len(self.basic_list)):
            if self.basic_list[i]['name'] == status[i]['name']:
                self.basic_list[i]['status'] = status[i]['status']
        result = json.dumps(self.basic_list, ensure_ascii=False)
        self.sm.close()
        return HttpResponse(result, content_type="application/json")

class Status:
    def __init__(self):
        self.cur = datetime.now()

    def getStatus(self, searchManager, libraryNames):
        result = []
        days = ['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일']
        # 현재 요일, 시각, 분
        for i in range(len(libraryNames)):
            data = searchManager.getOperateTime(libraryNames[i]['name'])
            # cur = datetime.now()
            curDay = self.cur.weekday()
            curHour = self.cur.hour
            curMinute = self.cur.minute

            closeDay = data['close_day'].replace(',',' ').split()
            if curDay < 5:
                open = list(map(int, data['every_open'].split(':')))
                close = list(map(int, data['every_close'].split(':')))
            elif curDay == 5:
                open = list(map(int, data['sat_open'].split(':')))
                close = list(map(int, data['sat_close'].split(':')))
            else:
                open = list(map(int, data['holiday_open'].split(':')))
                close = list(map(int, data['holiday_close'].split(':')))

            # 휴관일
            if days[curDay] in closeDay:
                result.append({'name':libraryNames[i]['name'], 'status':'close'})
                continue

            # 오픈 전
            if open[0] > curHour or (open[0]==curHour and open[1]>curMinute):
                result.append({'name':libraryNames[i]['name'], 'status':'close'})
                continue

            # 운영 종료
            if close[0] < curHour or (close[0]==curHour and close[1]<curHour):
                result.append({'name':libraryNames[i]['name'], 'status': 'close'})
                continue

            result.append({'name':libraryNames[i]['name'], 'status':'open'})
        return result

class LibraryDetailView(View):
    def get(self, request, name):
        sm = SearchManager('localhost', 'ssacuser', 'ssac123!@#', 'libweb')
        details = sm.getDetailedInfo(name)
        sm.close()
        context = {'result' : details}
        return render(request, 'search/detail.html', context)
        # return HttpResponse(result, content_type="application/json")

class SearchNaverView(View):
    def get(self, request, name):
        na = NaverApi()
        result = na.searchWebKr(name)
        result = json.dumps(result['items'], ensure_ascii=False)
        return HttpResponse(result, content_type="application/json")

libraries/search/templates/search/detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}도서관 상세정보 조회{% endblock %}

{% block content %}
<div class="courses-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12" style="width:100%">
                <div class="courses-inner res-mg-b-30">
                    {% for res in result %}
                    <div class="courses-title">
                        <h2>{{ res.name }}</h2>
                    </div>
                    <div class="courses-alaltic">
                        <span class="cr-ic-r"><span class="course-icon"><i class="fa fa-clock"></i></span> 1 Year</span>
                        <span class="cr-ic-r"><span class="course-icon"><i class="fa fa-heart"></i></span> 50</span>
                        <span class="cr-ic-r"><span class="course-icon"><i class="fa fa-dollar"></i></span> 500</span>
                    </div>
                    <div class="course-des">
                        <p><span><i class="fa fa-clock"></i></span> <b>휴관일:</b> &nbsp;{{ res.close_day }}</p>
                        <p><span><i class="fa fa-clock"></i></span> <b>평일오픈시각:</b> &nbsp;{{ res.every_open }}</p>
                        <p><span><i class="fa fa-clock"></i></span> <b>평일종료시각:</b> &nbsp;{{ res.every_close }}</p>
                        <p><span><i class="fa fa-clock"></i></span> <b>토요일오픈시각:</b> &nbsp;{{ res.sat_open }}</p>
                        <p><span><i class="fa fa-clock"></i></span> <b>토요일종료시각:</b> &nbsp;{{ res.sat_close }}</p>
                        <p><span><i class="fa fa-clock"></i></span> <b>공휴일오픈시각:</b> &nbsp;{{ res.holiday_open }}</p>
                        <p><span><i class="fa fa-clock"></i></span> <b>공휴일종료시각:</b> &nbsp;{{ res.holiday_close }}</p>
                        <p><span><i class="fa fa-clock"></i></span> <b>좌석수:</b> &nbsp;{{ res.seats }}</p>
                        <p><span><i class="fa fa-clock"></i></span> <b>도서자료수:</b> &nbsp;{{ res.books }}</p>
                        <p><span><i class="fa fa-clock"></i></span> <b>대여가능권수:</b> &nbsp;{{ res.loanable_books }}</p>
                        <p><span><i class="fa fa-clock"></i></span> <b>대여가능일수:</b> &nbsp;{{ res.loanable_days }}</p>
                        <p><span><i class="fa fa-clock"></i></span> <b>도로명주소:</b> &nbsp;{{ res.address }}</p>
                        <p><span><i class="fa fa-clock"></i></span> <b>전화번호:</b> &nbsp;{{ res.phone_number }}</p>
                    </div>
                    {% endfor %}
                    <div class="product-buttons">
                        <button type="button" class="button-default cart-btn api-btn">네이버에서 조회</button>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- map -->
<div class="data-map-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" style="display:none">
                <div class="sparkline8-list responsive-mg-b-30">
                    <div class="sparkline8-hd">
                        <div class="main-sparkline8-hd">
                            <h1>Data Map Style 1</h1>
                        </div>
                    </div>
                    <div class="sparkline8-graph">
                        <div class="data-map-single">
                            <div id="basic_map"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" style="display:none">
                <div class="sparkline9-list">
                    <div class="sparkline9-hd">
                        <div class="main-sparkline9-hd">
                            <h1>남기고 싶은 지도</h1>
                        </div>
                    </div>
                    <div class="sparkline9-graph">
                        <div class="data-map-single">
                            <div id="selected_map"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" style="width:100%">
                <div class="sparkline7-list mg-tb-30 responsive-mg-b-0">
                    <div class="sparkline7-hd">
                        <div class="main-spark7-hd">
                            <h1>Data Map Style 3</h1>
                        </div>
                    </div>
                    <div class="sparkline7-graph">
                        <div class="data-map-single">
                            <div id="usa_map"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" style="display:none">
                <div class="sparkline10-list mg-tb-30">
                    <div class="sparkline10-hd">
                        <div class="main-sparkline10-hd">
                            <h1>Data Map Style 4</h1>
                        </div>
                    </div>
                    <div class="sparkline10-graph">
                        <div class="data-map-single">
                            <div id="arc_map"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" style="display:none">
                <div class="sparkline11-list res-mg-b-30">
                    <div class="sparkline11-hd">
                        <div class="main-spark7-hd">
                            <h1>Data Map Style 5</h1>
                        </div>
                    </div>
                    <div class="sparkline11-graph">
                        <div class="data-map-single basic-choropleth">
                            <div id="basic_choropleth" style="position: relative; width: 100%; height: 100%;"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" style="display:none">
                <div class="sparkline12-list">
                    <div class="sparkline12-hd">
                        <div class="main-sparkline12-hd">
                            <h1>Data Map Style 6</h1>
                        </div>
                    </div>
                    <div class="sparkline12-graph">
                        <div class="data-map-single">
                            <div id="projection_map" style="position: relative; width: 100%; height: 400px;"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra-script%}
<script src="/static/js/data-map/d3.min.js"></script>
<script src="/static/js/data-map/topojson.js"></script>
<script src="/static/js/data-map/datamaps.all.min.js"></script>
<script src="/static/js/data-map/data-maps-active.js"></script>
<script src="/static/js/tab.js"></script>
<script>
    $(function(){
        $('.api-btn').on('click', function(event){
            event.preventDefault();
            event.stopPropagation();

            let name = $('.courses-title h2').html();

            $.ajax({
                "url": "/search/detail/naver/" + name,
                "method": "GET",
                "dataType": "json",
                "success": function(data, status, xhr){
                    for (let i=0; i < data.length; i++) {
                        alert(data[i]['title']);
                        alert(data[i]['description']);
                    }
                },
                "error": function(xhr, status, err){
                    alert("Cannot search in Naver.");
                }
            });
        });
    });
</script>
{% endblock %}

libraries/search/templates/search/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}전국도서관 조회{% endblock %}

{% block content %}
<div class="static-table-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="breadcome-list">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <div class="breadcome-heading">
                                <form action="" id="setRows" role="search" class="sr-input-func">
                                    <div class="row">
                                        <p>
                                            페이지당
                                            <input type="text" name="rows" placeholder="rows per page" value="15"
                                                class="search-int form-control">
                                            개의 정보 조회
                                        </p>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="row" id="tb-area">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" style="width:100%">
                <div class="product-status-wrap sparkline8-list">
                    <div class="sparkline8-hd">
                        <div class="main-sparkline8-hd">
                            <h1>도서관 기본 정보</h1>
                        </div>
                    </div>
                    <div class="sparkline8-graph">
                        <div class="static-table-list asset-inner">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>도서관명</th>
                                        <th>현재운영상태</th>
                                        <th>시도명</th>
                                        <th>군구명</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra-script %}
<script>
    $(function () {
        $.ajax({
            "url": "/search/all",
            "method": "GET",
            "dataType": "json",
            "success": function (data, status, xhr) {
                for (let i = 0; i < data.length; ++i) {
                    row = "<tr>";
                    let url = "{% url 'search:detail' 1234 %}".replace(/1234/, data[i]['name'].replaceAll(' ', '%20'));
                    row += "<td>" + (i + 1) + "</td>";
                    row += "<td><a class='lib-name'" + " href=" + url + ">" + data[i]['name'] + "</a></td>";
                    if (data[i]['status'] == 'open') {
                        row += '<td><button class="pd-setting">' + data[i]['status'] + '</button></td>';
                    }
                    else {
                        row += '<td><button class="ds-setting">' + data[i]['status'] + '</button></td>';
                    }
                    row += "<td>" + data[i]['sido_nm'] + "</td>";
                    row += "<td>" + data[i]['gungu_nm'] + "</td></tr>";
                    $('.table>tbody').append(row);
                }
            },
            "complete": function (xhr, status) {
                $('#setRows').submit();
            }
        });

        let $setRows = $('#setRows');
        $('#setRows').submit(function (e) {
            e.preventDefault();
            let rows = $('[name="rows"]').val() * 1;

            $('#nav').remove();
            let $tb = $('.table');
            let $area = $('#tb-area');
            $area.after('<div id="nav">');

            $('#nav').wrap('<div></div>');
            $('#nav').parent().addClass("col-lg-6 col-md-6 col-sm-6 col-xs-12").css('width', '100%');
            $('#nav').parent().wrap('<div></div>');
            $('#nav').parent().parent().addClass("row");

            let $tr = $($tb).find('tbody tr');
            $tr.removeAttr('style');
            let totRows = $tr.length; // tr 태그들의 길이

            let totPages = Math.ceil(totRows / rows); // 전체 페이지 수
            for (let i = 0; i < totPages; i++) {
                $('<a href="#"></a>') // 페이지 버튼들에 a태그 추가
                    .attr('rel', i)
                    .html(i + 1)
                    .appendTo('#nav');
                if (i == 0) {
                    $('#nav a').addClass('active');
                }
            }
            $tr.addClass('off-screen')
                .slice(0, rows)
                .removeClass('off-screen');

            let $pagingLink = $('#nav a'); // 페이지 버튼
            $pagingLink.on('click', function (event) { // 버튼이 눌러지면
                event.preventDefault();

                let $this = $(this);
                if ($this.hasClass('active')) {
                    return;
                }
                $pagingLink.removeClass('active');
                $this.addClass('active'); // 눌러진 페이지 버튼을 active 클래스로

                let curPage = $this.attr('rel');
                let startItem = curPage * rows;
                let endItem = startItem + rows;

                $tr.css('opacity', '0.0')
                    .addClass('off-screen')
                    .slice(startItem, endItem)
                    .removeClass('off-screen')
                    .css('display', '')
                    .animate({ opacity: 1 }, 300);

                $('.off-screen').css("display", "none");
                $('#nav').css({ 'width': '100%', 'text-align': 'center' });
                $('#nav a').css({
                    'display': 'inline-block', 'padding': '3px 5px',
                    'margin-right': '10px', 'background': 'none', 'color': '#006DF0',
                    'text-decoration': 'none'
                });
                $('#nav a.active').css({ 'background': '#006DF0', 'color': '#fff' });
            });

            $pagingLink.filter(':first').addClass('active');
            $('.off-screen').css("display", "none");
            $('#nav').css({ 'width': '100%', 'text-align': 'center' });
            $('#nav a').css({
                'display': 'inline-block', 'padding': '3px 5px',
                'margin-right': '10px', 'background': 'none', 'color': '#006DF0',
                'text-decoration': 'none'
            });
            $('#nav a.active').css({ 'background': '#006DF0', 'color': '#fff' });
        });

        $('.search-btn').on('click', function (event) {
            event.preventDefault();
            event.stopPropagation();

            let name = $('.search-int').val();

            $.ajax({
                "url": "/search/list/" + name,
                "method": "GET",
                "dataType": "json",
                "success": function (data, status, xhr) {
                    $('.table > tbody').empty();
                    for (let i = 0; i < data.length; ++i) {
                        row = "<tr>";
                        let url = "{% url 'search:detail' 1234 %}".replace(/1234/, data[i]['name'].replaceAll(' ', '%20'));
                        row += "<td>" + (i + 1) + "</td>";
                        row += "<td><a class='lib-name'" + " href=" + url + ">" + data[i]['name'] + "</a></td>";
                        if (data[i]['status'] == 'open') {
                            row += '<td><button class="pd-setting">' + data[i]['status'] + '</button></td>';
                        }
                        else {
                            row += '<td><button class="ds-setting">' + data[i]['status'] + '</button></td>';
                        }
                        row += "<td>" + data[i]['sido_nm'] + "</td>";
                        row += "<td>" + data[i]['gungu_nm'] + "</td></tr>";
                        $('.table>tbody').append(row);
                    }
                },
                "complete": function (xhr, status) {
                    $('#setRows').submit();
                }
            });
        });
    });
</script>
{% endblock %}